### ISSUE TITLE
Refactor to one branch

### ISSUE THREAD

**Issue by borisson** [mkalkbrenner/search_api_integration_tests#19]
I've been wondering why we're using 2 branches here (for drupal.current and drupal.next), is there a way we can actually do that as matrix instead of additional branches? That would make more sense as the extra branches make creating pull-requests harder. It also splits up the overview of the state into 2 different travis builds.

**Comment by borisson** [comment]
I think that would also make it easier to support 8.4, now that that branch has been opened, but we'd have to discuss this. 8.2 won't be supported for much longer, so soon we'd have to test on 8.3+8.4 anyway.

I'm open to arguments on why I'm wrong though.

**Comment by mkalkbrenner** [comment]
Basically you have to install all required Drupal cores is separate sub folders and run all tests.
The reason why I prefer separate branches is that you can test them individually on travis and see for example the tests fpr 8.3 are green while the tests for 8.4 are failing.

**Comment by mkalkbrenner** [comment]
Done. master now covers all modules, PHP versions and different drupal cores and drush versions.
