### ISSUE TITLE
Solr tests are failing due to misconfiguration 

### ISSUE THREAD

**Issue by itsekhmistro** [mkalkbrenner/search_api_integration_tests#3]
Example output of failed tests 
https://travis-ci.org/mkalkbrenner/search_api_integration_tests/jobs/166441675

When executing simple tests:
`php core/scripts/run-tests.sh --verbose --color --concurrency 4 --php`which php`--url http://localhost:8888 --directory modules/contrib --types Simpletest | tee /tmp/test.txt ; export TEST_EXIT=${PIPESTATUS[0]} ; echo $TEST_EXIT`

> Drupal\search_api_solr\Tests\IntegrationTest                 245 passes  10 fails                 73 messages
> Drupal\search_api_solr\Tests\ViewsTest                       208 passes 122 fails                 67 messages

All test related to search results are failing due to broken connection to Solr service.

This problem can be easily reproduced locally if you run the same test command with completely stopped Solr server (or for example with incorrect Core name installed).

Meanwhile when the SOLR connection is configured properly all ViewsTest are passing with 100% pass.

**Comment by nickveenhof** [comment]
Great that you found this! 
What is the suggested course of action? Is there a PR that we can review to fix this?

**Comment by mkalkbrenner** [comment]
Solr tests are now passing:
https://travis-ci.org/mkalkbrenner/search_api_integration_tests/builds/167422204
